vim.cmd('packadd! cfilter')
-- use { 'lervag/vimtex' }
use { 'RRethy/nvim-align' }
use { 'RRethy/nvim-base16' }
use { 'RRethy/nvim-hotline' }
use { 'RRethy/nvim-shopify-dev' }
use { 'RRethy/nvim-treesitter-endwise' }
use { 'RRethy/nvim-treesitter-textsubjects' }
use { 'RRethy/vim-eunuch' }
use { 'RRethy/vim-illuminate' }
use { 'RRethy/vim-lacklustertab' }
use { 'RRethy/vim-tranquille' }
use { 'editorconfig/editorconfig-vim' }
use { 'hashivim/vim-terraform' }
use { 'justinmk/vim-dirvish' }
use { 'kyazdani42/nvim-web-devicons' }
use { 'lukas-reineke/indent-blankline.nvim' }
use { 'mfussenegger/nvim-lint' }
use { 'neovim/nvim-lspconfig' }
use { 'numToStr/Comment.nvim' }
use { 'nvim-lua/plenary.nvim' }
use { 'nvim-lua/popup.nvim' }
use { 'nvim-telescope/telescope-fzf-native.nvim' }
use { 'nvim-telescope/telescope-fzy-native.nvim' }
use { 'nvim-telescope/telescope-symbols.nvim' }
use { 'nvim-telescope/telescope.nvim' }
use { 'nvim-treesitter/nvim-treesitter' }
use { 'nvim-treesitter/nvim-treesitter-refactor' }
use { 'nvim-treesitter/nvim-treesitter-textobjects' }
use { 'nvim-treesitter/playground' }
use { 'rcarriga/nvim-notify' }
use { 'romainl/vim-cool' }
use { 'shopify/vim-repoify' }
use { 'tpope/vim-abolish' }
use { 'tpope/vim-fugitive' }
use { 'tpope/vim-projectionist' }
use { 'tpope/vim-repeat' }
use { 'tpope/vim-rhubarb' }
use { 'tpope/vim-surround' }
use { 'vim-test/vim-test' }
use { 'williamboman/nvim-lsp-installer' }
-- use { 'wincent/loupe' }
use { 'windwp/nvim-autopairs' }
