use { 'RRethy/nvim-align' }
use { 'RRethy/nvim-animator' }
use { 'RRethy/nvim-base16' }
use { 'RRethy/nvim-hotline' }
use { 'RRethy/nvim-sandbox' }
use { 'RRethy/nvim-sourcerer' }
use { 'RRethy/vim-eunuch' }
use { 'RRethy/vim-hexokinase' }
use { 'RRethy/vim-illuminate' }
use { 'RRethy/vim-lacklustertab' }
use { 'RRethy/vim-tranquille' }
use { 'editorconfig/editorconfig-vim' }
use { 'justinmk/vim-dirvish' }
use { 'lervag/vimtex' }
use { 'lukas-reineke/indent-blankline.nvim' }
use { 'neovim/nvim-lspconfig' }
use { 'nvim-lua/plenary.nvim' }
use { 'nvim-lua/popup.nvim' }
use { 'nvim-telescope/telescope-fzf-native.nvim' }
use { 'nvim-telescope/telescope-fzy-native.nvim' }
use { 'nvim-telescope/telescope-symbols.nvim' }
use { 'nvim-telescope/telescope.nvim' }
use { 'nvim-treesitter/nvim-treesitter' }
use { 'nvim-treesitter/nvim-treesitter-refactor' }
use { 'nvim-treesitter/nvim-treesitter-textobjects' }
use { 'nvim-treesitter/playground' }
use { 'romainl/vim-cool' }
use { 'tpope/vim-abolish' }
use { 'tpope/vim-commentary' }
use { 'tpope/vim-fugitive' }
use { 'tpope/vim-projectionist' }
use { 'tpope/vim-repeat' }
use { 'tpope/vim-rhubarb' }
use { 'tpope/vim-surround' }
use { 'vim-test/vim-test' }
use { 'wincent/vcs-jump' }
